#!/usr/bin/env bash
set -euo pipefail

target="${1:-.}"
root="$(cd "$(dirname "$0")/.." && pwd)"
project="$(cd "$target" && pwd)"

cd "$project"
mkdir -p build

read_yaml_value() {
  local key="$1"
  local file="${2:-neuroforge.yml}"
  [[ -f "$file" ]] || return 1
  awk -F: -v key="$key" '
    $1 ~ "^[[:space:]]*" key "$" {
      sub(/^[[:space:]]*/, "", $2)
      sub(/[[:space:]]*$/, "", $2)
      gsub(/^"|"$/, "", $2)
      print $2
      exit
    }
  ' "$file"
}

repo_from_git() {
  git remote get-url origin 2>/dev/null | sed -E 's#^git@github.com:##; s#^https://github.com/##; s#\.git$##'
}

repo="$(read_yaml_value repository || true)"
if [[ -z "${repo:-}" || "$repo" == "pending" ]]; then
  repo="$(repo_from_git || true)"
fi

platform="$(
  awk '
    /^platform:/ { in_platform=1; next }
    /^[^[:space:]]/ { in_platform=0 }
    in_platform && $2 ~ /true|pending/ {
      key=$1
      gsub(":", "", key)
      if ($2 == "true") { print key; exit }
      if (first == "") first=key
    }
    END { if (first != "") print first }
  ' neuroforge.yml 2>/dev/null || true
)"
[[ -n "$platform" ]] || platform="pending"

language="$(read_yaml_value language || true)"
[[ -n "$language" ]] || language="pending"

compliance="$("$root/scripts/check-neuroforge-compliance.sh" "$project")"
nf_badge="$root/badges/generated/neuroforge.svg"
nf_alt="Neuro Forge"
if [[ "$compliance" != "compliant" ]]; then
  nf_alt="Neuro Forge pending"
fi

custom_base="badges/generated"
if [[ "$project" != "$root" ]]; then
  custom_base="$(perl -MFile::Spec -e 'print File::Spec->abs2rel($ARGV[0], $ARGV[1])' "$root/badges/generated" "$project")"
fi

badges=()
json_items=()

add_badge() {
  local id="$1"
  local label="$2"
  local markdown="$3"
  badges+=("$markdown")
  json_items+=("{\"id\":\"$id\",\"label\":\"$label\",\"markdown\":\"${markdown//\"/\\\"}\"}")
}

add_badge "neuroforge" "$nf_alt" "![${nf_alt}](${custom_base}/neuroforge.svg)"

if [[ -n "${repo:-}" && "$repo" != "pending" && "$repo" == */* ]]; then
  add_badge "release" "Release" "![Release](https://img.shields.io/github/v/release/${repo}?label=release&color=111111&labelColor=f5f5f5)"
  if [[ -d .github/workflows ]]; then
    build_workflow="$(find .github/workflows -type f \( -name '*build*.yml' -o -name '*build*.yaml' \) | head -1 | xargs basename 2>/dev/null || true)"
    test_workflow="$(find .github/workflows -type f \( -name '*test*.yml' -o -name '*test*.yaml' -o -name '*ci*.yml' -o -name '*ci*.yaml' \) | head -1 | xargs basename 2>/dev/null || true)"
    [[ -n "$build_workflow" ]] && add_badge "build" "Build" "![Build](https://img.shields.io/github/actions/workflow/status/${repo}/${build_workflow}?label=build&color=111111&labelColor=f5f5f5)"
    [[ -n "$test_workflow" ]] && add_badge "tests" "Tests" "![Tests](https://img.shields.io/github/actions/workflow/status/${repo}/${test_workflow}?label=tests&color=111111&labelColor=f5f5f5)"
  fi
  [[ -f LICENSE || -f LICENSE.md ]] && add_badge "license" "License" "![License](https://img.shields.io/github/license/${repo}?label=license&color=111111&labelColor=f5f5f5)"
  [[ "$language" != "pending" ]] && add_badge "language" "Language" "![Language](https://img.shields.io/github/languages/top/${repo}?label=language&color=111111&labelColor=f5f5f5)"
  add_badge "maintained" "Maintained" "![Maintained](https://img.shields.io/github/last-commit/${repo}?label=maintained&color=111111&labelColor=f5f5f5)"
fi

[[ "$platform" != "pending" ]] && add_badge "platform" "Platform" "![Platform](https://img.shields.io/badge/platform-${platform}-111111?labelColor=f5f5f5)"
add_badge "ai_assisted" "AI-assisted" "![AI-assisted](${custom_base}/ai-assisted.svg)"

{
  for badge in "${badges[@]}"; do
    printf '%s\n' "$badge"
  done
  printf '\n%s\n' "![Atypical ThinkR / 0SEC WorkR](${custom_base}/0sec-workr.svg)"
} > build/neuroforge-badges.md

{
  printf '{\n'
  printf '  "compliance": "%s",\n' "$compliance"
  printf '  "repository": "%s",\n' "${repo:-pending}"
  printf '  "platform": "%s",\n' "$platform"
  printf '  "language": "%s",\n' "$language"
  printf '  "badges": [\n'
  for i in "${!json_items[@]}"; do
    printf '    %s' "${json_items[$i]}"
    [[ "$i" == "$((${#json_items[@]} - 1))" ]] || printf ','
    printf '\n'
  done
  printf '  ],\n'
  printf '  "signature": {"id":"zero_sec_workr","markdown":"![Atypical ThinkR / 0SEC WorkR](%s/0sec-workr.svg)"}\n' "$custom_base"
  printf '}\n'
} > build/neuroforge-badges.json

cat build/neuroforge-badges.md

if [[ -f README.md ]] && grep -q '<!-- NEUROFORGE_BADGES:BEGIN -->' README.md && grep -q '<!-- NEUROFORGE_BADGES:END -->' README.md; then
  tmp="$(mktemp)"
  awk '
    /<!-- NEUROFORGE_BADGES:BEGIN -->/ {
      print
      print "<!-- Generated by scripts/generate-badges.sh -->"
      while ((getline line < "build/neuroforge-badges.md") > 0) print line
      in_block=1
      next
    }
    /<!-- NEUROFORGE_BADGES:END -->/ {
      in_block=0
      print
      next
    }
    !in_block { print }
  ' README.md > "$tmp"
  mv "$tmp" README.md
fi
